### ISSUE TITLE
Error running json-server on Windows

### ISSUE THREAD

**Issue by justbearcause** [ngduc/parcelui#7]
I'm getting an error running `yarn dev` on Windows:
```
> $(cat .env | xargs -n1 echo export) && json-server ./tools/mockData/jsonData.js --port $API_PORT

'$' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 255
```

**Comment by ngduc** [comment]
@aalitvinenko  I'd recommend you use Windows powershell or cygwin to have better bash environment which understand "$" syntax. Please let me know if that works for you.
